[workspace]
authors = ["Tcc0403 <76503978+Tcc0403@users.noreply.github.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "pytorch_custom_ops"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.5.0.dev2025062305,<26"
pytest = ">=8.4.1,<9"

[system-requirements]
cuda = "12"  # Replace "12" with the specific CUDA version you intend to use
